2020-09-17 00:14:30,103 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 157749ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:19:30,577 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160412ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:24:30,387 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:29:30,314 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159661ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:34:30,103 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:39:30,100 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159912ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:44:29,924 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159763ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:49:30,052 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159961ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:54:29,583 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159426ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 00:59:29,569 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159422ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:04:29,847 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160147ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:09:29,684 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159572ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:14:30,662 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160541ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:19:28,605 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 157507ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:24:29,720 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 101080ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:29:28,603 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 158487ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:34:29,566 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160430ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:39:29,570 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:44:29,804 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160152ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:49:30,019 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 159914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 01:54:30,310 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 160212ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 04:57:59,435 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 10808803ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 07:58:01,941 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 10802409ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 08:26:01,069 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 1678505ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 09:09:27,206 ERROR 14640 [-/127.0.0.1/-/10ms POST /mqtt/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'energy-platform.t800g2' doesn't exist
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `T800G2`
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'energy-platform.t800g2' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT COUNT(*) as count FROM `T800G2`"
name: "ER_NO_SUCH_TABLEError"
pid: 14640
hostname: J9MO9BU01VTBF92

2020-09-17 09:11:24,642 ERROR 17700 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 09:51:47,309 ERROR 14712 [-/127.0.0.1/-/7ms POST /mqtt/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'energy-platform.mqtt1' doesn't exist
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `mqtt1`
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'energy-platform.mqtt1' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT COUNT(*) as count FROM `mqtt1`"
name: "ER_NO_SUCH_TABLEError"
pid: 14712
hostname: J9MO9BU01VTBF92

2020-09-17 10:01:25,451 ERROR 19452 [-/127.0.0.1/-/44ms POST /mqtt/list] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'startTime' in 'where clause'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: SELECT `content` FROM `mqtt2` WHERE `startTime` = '' AND `endTime` = '' ORDER BY `id` DESC LIMIT 0, 10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'startTime' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT `content` FROM `mqtt2` WHERE `startTime` = '' AND `endTime` = '' ORDER BY `id` DESC LIMIT 0, 10"
name: "ER_BAD_FIELD_ERRORError"
pid: 19452
hostname: J9MO9BU01VTBF92

2020-09-17 10:14:26,415 ERROR 17700 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 10:14:31,795 ERROR 16692 [-/127.0.0.1/-/48ms POST /mqtt/list] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '10' at line 1
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: SELECT content  FROM mqtt2 WHERE time>0 AND time< 1600308871785 ORDER BY id DESC LIMIT 0 10
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '10' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT content  FROM mqtt2 WHERE time>0 AND time< 1600308871785 ORDER BY id DESC LIMIT 0 10"
name: "ER_PARSE_ERRORError"
pid: 16692
hostname: J9MO9BU01VTBF92

2020-09-17 12:27:01,949 ERROR 17700 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 14:18:39,605 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 3913261ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 14:33:37,590 ERROR 17700 nodejs.ClusterClientNoResponseError: client no response in 177830ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 17700
hostname: J9MO9BU01VTBF92

2020-09-17 20:41:16,429 ERROR 3644 nodejs.ClusterClientNoResponseError: client no response in 2191137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3644
hostname: J9MO9BU01VTBF92

2020-09-17 23:56:05,971 ERROR 3644 nodejs.ClusterClientNoResponseError: client no response in 10809230ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3644
hostname: J9MO9BU01VTBF92

2020-09-18 00:11:31,361 ERROR 3644 nodejs.ClusterClientNoResponseError: client no response in 924762ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3644
hostname: J9MO9BU01VTBF92

