2020-09-24 00:30:29,969 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159585ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 00:35:29,859 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 00:40:30,081 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160100ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 00:45:30,240 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 00:50:30,270 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159430ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 00:55:30,544 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159842ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:00:29,633 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 158645ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:05:29,806 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:10:29,805 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159767ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:15:29,616 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159777ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:20:30,113 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160459ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:25:31,256 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:30:30,600 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 158668ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:35:29,618 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 158911ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:40:29,822 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160155ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:45:29,664 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 159827ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:50:30,113 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 80441ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 01:55:30,307 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 160182ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 04:57:59,319 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 10808541ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 07:58:00,844 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 10801367ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 08:13:40,389 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 939526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 12:19:28,441 ERROR 4724 nodejs.ClusterClientNoResponseError: client no response in 406187ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4724
hostname: J9MO9BU01VTBF92

2020-09-24 19:24:53,128 ERROR 4724 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4724
hostname: J9MO9BU01VTBF92

